version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: sportsbook-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: sportsbook
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: sportsbook-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mongodb_data: